### ISSUE TITLE
CSI cinder only use metadata ,not consider config drive

### ISSUE THREAD

**Issue by jichenjc** [kubernetes/cloud-provider-openstack#479]
pkg/csi/cinder/openstack/openstack_metadata.go only consider metadata service ,not config drive now

**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:
same flow to cloud proivder and CSI
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by adisky** [comment]
/remove-lifecycle rotten
still needed

**Comment by adisky** [comment]
@jichenjc any update on this??

**Comment by kayrus** [comment]
This issue was fixed in #920
cc @jichenjc

**Comment by jichenjc** [comment]
yes , thanks for the reminder ~

**Comment by mape90** [comment]
Actually this issue is still not fixed. As that fix only added search order to use either mounter or metadataservice. It never uses config drive. I have opened issue https://github.com/kubernetes/cloud-provider-openstack/issues/1030 for this. Solution to solve this would be simple by just using pkg/util/metadata/metadata.go which already implements search order and uses both config drive and metadata service.
